version: 1.0
provider:
  name: openfaas
  gateway: http://faasd-gateway:8080
functions:
  gce-toggle:
    lang: golang-middleware
    handler: ./gce-toggle
    image: efbar/serverless-libs:gce-toggle-0.0.1
    secrets:
      - sa-gcp # faas-cli secret create sa-gcp --from-file=/path/to/file/sa-key.json
    build_args:
      GO111MODULE: on
    environment:
      PROJECT_ID: "functest-307416"
      REGION: "us-central1"
  nomad-jobs-list:
    lang: golang-middleware
    handler: ./nomad-jobs-list
    image: efbar/serverless-libs:nomad-jobs-list-0.0.1
    build_args:
      GO111MODULE: on
  functions:
    nomad-nodes-list:
      lang: golang-middleware
      handler: ./nomad-nodes-list
      image: efbar/serverless-libs:nomad-nodes-list-0.0.1
    build_args:
      GO111MODULE: on
