version: 1.0
provider:
  name: openfaas
  gateway: http://faasd-gateway:8080
functions:
  gce-toggle:
    lang: golang-middleware
    handler: ./gce-toggle
    image: efbar/more-serverless:gce-toggle-0.0.1
    secrets:
      - sa-gcp # faas-cli secret create sa-gcp --from-file=/path/to/file/sa-key.json
    build_args:
      GO111MODULE: on
    environment:
      PROJECT_ID: "functest-307416"
      REGION: "us-central1"
  nomad-job-status:
    lang: golang-middleware
    handler: ./nomad-job-status
    image: efbar/more-serverless:nomad-job-status-0.0.1
    build_args:
      GO111MODULE: on
  nomad-node-status:
    lang: golang-middleware
    handler: ./nomad-node-status
    image: efbar/more-serverless:nomad-node-status-0.0.1
    build_args:
      GO111MODULE: on
