version: 1.0
provider:
  name: openfaas
  gateway: http://faasd-gateway:8080
functions:
  gce-toggle:
    lang: golang-middleware
    handler: ./gce-toggle
    image: efbar/gce-toggle:1.0.0
    secrets:
      - gce-sa-gcp # faas-cli secret create sa-gcp --from-file=/path/to/file/sa-key.json
    build_args:
      GO111MODULE: on
    environment:
      PROJECT_ID: "functest-307416"
      REGION: "us-central1"
  gce-list:
    lang: golang-middleware
    handler: ./gce-list
    image: efbar/gce-list:1.0.0
    secrets:
      - gce-sa-gcp # faas-cli secret create sa-gcp --from-file=/path/to/file/sa-key.json
    build_args:
      GO111MODULE: on
    environment:
      PROJECT_ID: "functest-307416"
      REGION: "us-central1"
  nomad-job-status:
    lang: golang-middleware
    handler: ./nomad-job-status
    image: efbar/nomad-job-status:1.0.0
    build_args:
      GO111MODULE: on
  nomad-node-status:
    lang: golang-middleware
    handler: ./nomad-node-status
    image: efbar/nomad-node-status:1.0.0
    build_args:
      GO111MODULE: on
  nomad-server-members:
    lang: golang-middleware
    handler: ./nomad-server-members
    image: efbar/nomad-server-members:1.0.0
    build_args:
      GO111MODULE: on
  consul-members:
    lang: golang-middleware
    handler: ./consul-members
    image: efbar/consul-members:1.0.0
    build_args:
      GO111MODULE: on
  consul-catalog-services:
    lang: golang-middleware
    handler: ./consul-catalog-services
    image: efbar/consul-catalog-services:1.0.0
    build_args:
      GO111MODULE: on
  consul-op-raft-list:
    lang: golang-middleware
    handler: ./consul-op-raft-list
    image: efbar/consul-op-raft-list:1.0.0
    build_args:
      GO111MODULE: on
  vault-status:
    lang: golang-middleware
    handler: ./vault-status
    image: efbar/vault-status:1.0.0
    build_args:
      GO111MODULE: on
  vault-kv-get:
    lang: golang-middleware
    handler: ./vault-kv-get
    image: efbar/vault-kv-get:1.0.0
    build_args:
      GO111MODULE: on
  vault-kv-put:
    lang: golang-middleware
    handler: ./vault-kv-put
    image: efbar/vault-kv-put:1.0.0
    build_args:
      GO111MODULE: on
  vault-transit:
    lang: golang-middleware
    handler: ./vault-transit
    image: efbar/vault-transit:1.0.0
    build_args:
      GO111MODULE: on
  slack-message:
    lang: golang-middleware
    handler: ./slack-message
    image: efbar/slack-message-0.9.0
    build_args:
      GO111MODULE: on
