version: 1.0
provider:
  name: openfaas
  gateway: http://faasd-gateway:8080
functions:
  gce-toggle:
    lang: golang-middleware
    handler: ./gce-toggle
    image: efbar/more-serverless:gce-toggle-0.0.1
    secrets:
      - sa-gcp # faas-cli secret create sa-gcp --from-file=/path/to/file/sa-key.json
    build_args:
      GO111MODULE: on
    environment:
      PROJECT_ID: "functest-307416"
      REGION: "us-central1"
  nomad-job-status:
    lang: golang-middleware
    handler: ./nomad-job-status
    image: efbar/more-serverless:nomad-job-status-0.0.1
    build_args:
      GO111MODULE: on
  nomad-node-status:
    lang: golang-middleware
    handler: ./nomad-node-status
    image: efbar/more-serverless:nomad-node-status-0.0.1
    build_args:
      GO111MODULE: on
  nomad-server-members:
    lang: golang-middleware
    handler: ./nomad-server-members
    image: efbar/more-serverless:nomad-server-members-0.0.1
    build_args:
      GO111MODULE: on
  consul-members:
    lang: golang-middleware
    handler: ./consul-members
    image: efbar/more-serverless:consul-members-0.0.1
    build_args:
      GO111MODULE: on
  consul-catalog-services:
    lang: golang-middleware
    handler: ./consul-catalog-services
    image: efbar/more-serverless:consul-catalog-services-0.0.1
    build_args:
      GO111MODULE: on
  consul-op-raft-list:
    lang: golang-middleware
    handler: ./consul-op-raft-list
    image: efbar/more-serverless:consul-op-raft-list-0.0.1
    build_args:
      GO111MODULE: on
  vault-status:
    lang: golang-middleware
    handler: ./vault-status
    image: efbar/more-serverless:vault-status-0.0.1
    build_args:
      GO111MODULE: on
  vault-read:
    lang: golang-middleware
    handler: ./vault-read
    image: efbar/vault-read:vault-read-0.0.1
    build_args:
      GO111MODULE: on
